version: '3.7'

services:

  api:
    container_name: zachsmith-api
    restart: always
    build: ./api/
    ports:
      - 8082:9000

  client:
    image: nginx:alpine
    container_name: zachsmith-browser-client
    restart: always
    volumes:
      - type: bind
        source: ./browser-client/index.html
        target: /usr/share/nginx/html/index.html
      - type: bind
        source: ./browser-client/nginx.conf
        target: /etc/nginx/conf.d/default.conf
    ports:
      - 8081:80